# %%

"""Build and test a pdchemchain scoring pipeline for REINVENT.

This script walks through the interactive development of a scoring pipeline
that calculates drug-likeness properties.  The pipeline is saved as YAML and
used by the ``PdChemChain`` REINVENT scoring component in the RL step.

Prerequisites:
    - Run ``reinvent 01_sample_prior.toml`` first to generate prior_sample.csv
    - pdchemchain and rdkit must be installed

The pipeline computes: MolWt, MolLogP, TPSA, NumHDonors, NumHAcceptors.
REINVENT will pick individual columns as scoring endpoints with separate
weights and transforms.
"""

# %% Imports
import pandas as pd

from pdchemchain.links.chemistry import MolFromSmiles, RDKitDescriptors

# %% Load the prior sample
# Generated by: reinvent 01_sample_prior.toml
df = pd.read_csv("prior_sample.csv")
print(f"Loaded {len(df)} SMILES from prior")
df.head()

# %% Step 1: Convert SMILES to RDKit molecules
# This is always the first step -- downstream links need the ROMol column.
mol_from_smiles = MolFromSmiles(in_column="SMILES")

mol_from_smiles(df.head(5))

# %% Step 2: Calculate descriptors
# Choose properties we want REINVENT to optimise.
descriptors = RDKitDescriptors(
    descriptors=["MolWt", "MolLogP", "TPSA", "NumHDonors", "NumHAcceptors"]
)

# Build the chain and test on a small sample
chain = mol_from_smiles + descriptors

chain(df.head(5))

# %% Run on the full prior sample to check distributions
result = chain(df)
print(f"Processed {len(result)} molecules, errors: {result.get('__error__', pd.Series()).notna().sum()}")
result[["SMILES", "MolWt", "MolLogP", "TPSA"]].describe()

# %% Quick distribution plots
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 2, figsize=(10, 8))

for ax, col in zip(axes.flat, ["MolLogP", "TPSA",  "MolWt", "NumHDonors"]):
    result[col].dropna().hist(bins=50, ax=ax, alpha=0.7)
    ax.set_title(col)
    ax.set_ylabel("Count")

fig.suptitle("Prior sample property distributions", fontsize=14)
fig.tight_layout()
plt.show()

# %% Set log level before saving
# pdchemchain serialises the log level into the YAML.  DEBUG is useful
# during interactive development, but makes REINVENT logs very chatty
# (every row and column assertion is logged).  Set to INFO for production.
chain.set_log_level("INFO")

# %% Save the scoring pipeline
# This YAML is simply referenced by the PdChemChain component in the RL config .toml file.
chain.to_config_file("scoring_pipeline.yaml")
print("Saved scoring_pipeline.yaml")

# %% Verify: reload and run
from pdchemchain.io_utilities import load_chain

reloaded = load_chain("scoring_pipeline.yaml")
test_result = reloaded(df.head(3))
test_result[["SMILES", "MolWt", "MolLogP", "TPSA"]]

# %%
